<?php

namespace AppBundle\Repository;

/**
 * DatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatesRepository extends \Doctrine\ORM\EntityRepository
{
}
